### Cadastrar Usuário ###

POST http://localhost:3003/signup
Content-Type: application/json

{
    "name": "Matheus",
    "email": "Matheus@gmail.com",
    "password": "xablauzin"
}

### Entrar na Conta ###

POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "Matheus@gmail.com",
    "password": "xablauzin"
}

#### TOKEN ####

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgzODk2ZjYxLTJkZDItNDliMC04ODVmLWE5ZTAzMjZiODNmZiIsImVtYWlsIjoiTWF0aGV1c0BnbWFpbC5jb20iLCJpYXQiOjE2NTY3ODUxMzksImV4cCI6MTY1Njc4ODczOX0.rQjzDUfq7XRvcvy7TArmb7tzn07xMpzGZdab4pyB4HM

### Pegar Perfil ###

GET http://localhost:3003/user/profile
Authorization: {{token}}

### Pegar Outros Perfis ###

GET http://localhost:3003/user/734220a3-871a-46b4-8de6-e39bbc8bc4db
Authorization: {{token}}

### Criar Receita ###

POST http://localhost:3003/recipe
Content-Type: application/json
Authorization: {{token}}

{
    "title": "Ovo",
    "description": "Quebre a casca do ovo levemente, em seguida abre a casca em cima de uma frigideira, frite o ovo com manteiga/azeite/oleo, vire o ovo quando achar necessário, e depois só comer."
}

### Pegar Receita ###

GET http://localhost:3003/recipes/f0e42a72-625b-4e49-8319-1660f86ab770
Authorization: {{token}}
