### Send Form ###

POST http://localhost:3003/form
Content-Type: application/json

{
    "firstName": "Matheus",
    "lastName": "Barros",
    "participation": 47
}

### Get Data ###

GET http://localhost:3003/form

### Del Data ###

DELETE http://localhost:3003/form
